name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "SnowGirl"
          replace: "SaintAries"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome to Saint Aries'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: idzero23
          commit_user_email: imboost@gmail.com
          commit_author: idzero23 <imboost@gmail.com>
